vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    formateurs:
      uri_prefix: /images/formateurs
      upload_destination: "%kernel.project_dir%/public/images/formateurs"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
   